services:
  - type: web
    name: promo-backend # Имя сервиса
    env: python
    # Указываем скрипт сборки
    buildCommand: "./build.sh"
    # Команда запуска с Gunicorn
    startCommand: "gunicorn ig_parser_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: promo-db # Имя БД на Render (см. ниже)
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10 # Укажи свою версию Python
      - key: DEBUG # Установим в False
        value: False

  - type: pserv         # Тип сервиса: PostgreSQL
    name: promo-db      # Имя сервиса на Render (как он будет виден в дашборде)
    plan: free          # Тарифный план
    databaseName: promo_db # Имя самой базы данных внутри Postgres
    user: promo_user   # Имя пользователя внутри Postgres