services:
  - type: web
    name: promo-backend # Имя веб-сервиса
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ig_parser_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: promo-db # Имя СЕРВИСА базы данных (должно совпадать ниже)
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10 # Укажи свою версию Python
      - key: DEBUG
        value: False

  - type: pserv         # Тип: PostgreSQL database service
    name: promo-db      # Имя самого СЕРВИСА базы данных на Render
    plan: free          # Тарифный план
    # --- ИСПРАВЛЕНИЯ ЗДЕСЬ, СОГЛАСНО ДОКУМЕНТАЦИИ ---
    databaseName: promo_db # Имя БАЗЫ ДАННЫХ внутри Postgres
    user: promo_user   # Имя ПОЛЬЗОВАТЕЛЯ внутри Postgres
    # postgresqlVersion: 15 # Можно раскомментировать и указать версию, если нужно