services:
  - type: web
    name: promo-backend # Имя сервиса
    env: python
    # Указываем скрипт сборки
    buildCommand: "./build.sh"
    # Команда запуска с Gunicorn
    startCommand: "gunicorn ig_parser_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: promo-db # Имя БД на Render (см. ниже)
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10 # Укажи свою версию Python
      - key: DEBUG # Установим в False
        value: False

  - type: pserv # База данных PostgreSQL
    name: promo-db
    databaseName: promo_db
    user: promo_user
    plan: free # Выбери тариф